### ISSUE TITLE
Ubuntu18.04 Setup

### ISSUE THREAD

**Issue by Durant35** [Durant35/Ubuntu-Install-Note#3]
```bash
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
garychan@ThinkPad-E470:~$ uname -a
Linux ThinkPad-E470 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- [x] [E470 无线网卡驱动异常，上不网](https://github.com/Durant35/System-Install-Note/issues/3#issuecomment-605400916)
    + Network by iPhone USB hotspot，先临时上网！！！
- [x] Keyboard Shortcuts changed with Ubuntu16.04!
- [x] [Why always resee `~/.snap` folder?](https://github.com/Durant35/System-Install-Note/issues/3#issuecomment-604805233)
- [x] [Topicons plus支持Wine等图标显示](https://github.com/Durant35/System-Install-Note/issues/3#issuecomment-604894734)
- [x] [合上盖子休眠，Wifi会自动断，导致VPN老要重连](https://github.com/Durant35/System-Install-Note/issues/3#issuecomment-605373120)
- [x] [XXX-X AAC decoder, H.264 (Main Profile) decoder are required to play the file, but are not installed.](https://github.com/Durant35/System-Install-Note/issues/3#issuecomment-879501664)
- [x] [Gnome Workspace多窗口](https://github.com/Durant35/System-Install-Note/issues/3#issuecomment-1256125987)
- [ ] [搜狗输入法](https://github.com/Durant35/Office-System-Pearls/issues/3#issuecomment-2342796867)

**Comment by Durant35** [comment]
## Why always resee `~/.snap` folder?

**Comment by Durant35** [comment]
## Why always resee ~/.snap folder?
> https://askubuntu.com/questions/1079203/why-is-gnome-system-monitor-on-18-04-installed-as-a-snap-by-default

```bash
$ sudo snap remove gnome-system-monitor
$ sudo apt install gnome-system-monitor
```

> https://askubuntu.com/questions/1039411/how-can-i-replace-snap-application-such-as-gnome-calculator-with-a-deb

```bash
# remove all snap packages except core and core18
$ sudo snap remove `sudo snap list | cut -d " " -f 1 | tail -n 2 | grep -v 'core' | tr '\n' ' '`
# Then install their .deb counterparts with:
$ sudo apt install gnome-calculator gnome-characters gnome-logs gnome-system-monitor
#  uninstall the whole Snapd ecosystem from your computer with:
$ sudo apt purge snapd squashfs-tools gnome-software-plugin-snap
```

**Comment by Durant35** [comment]
## Topicons plus支持Wine等图标显示
```bash
# 安装tweak-tool,用于定制化桌面
$ sudo apt install gnome-tweak-tool
$ sudo apt install gnome-shell-extension-top-icons-plus
# 重启后，打开tweak-tool->Extensions勾选Topicons plus，并可配置Top Center/Right...
```

**Comment by Durant35** [comment]
## 合上盖子休眠，Wifi会自动断，导致VPN老要重连
### 直接修改“合盖子不休眠”行为
> https://www.okcode.net/article/27012

```bash
$ sudo vim /etc/systemd/logind.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See logind.conf(5) for details.

[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5
#HandlePowerKey=poweroff
#HandleSuspendKey=suspend
#HandleHibernateKey=hibernate
# default: suspend
HandleLidSwitch=ignore
#HandleLidSwitchDocked=ignore
#PowerKeyIgnoreInhibited=no
#SuspendKeyIgnoreInhibited=no
#HibernateKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
#HoldoffTimeoutSec=30s
#IdleAction=ignore
#IdleActionSec=30min
#RuntimeDirectorySize=10%
#RemoveIPC=yes
#InhibitorsMax=8192
#SessionsMax=8192
#UserTasksMax=33%

## !!!! Recommend you to reboot then!!!
```

### 根源应该就是Ubuntu18.04合盖子的行为变了
> https://unix.stackexchange.com/questions/248033/configure-linux-laptop-to-switch-off-screen-but-otherwise-remain-running-when-li

```bash
$ sudo apt-get install vim
$ sudo vim /etc/systemd/logind.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See logind.conf(5) for details.

[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5
#HandlePowerKey=poweroff
#HandleSuspendKey=suspend
#HandleHibernateKey=hibernate
##
# The full set of possible values for HandleLidSwitch and HandleLidSwitchExternalPower is:
#  ignore, poweroff, reboot, halt, kexec, suspend, hibernate, hybrid-sleep, suspend-then-hibernate, and lock
# default: suspend
##
HandleLidSwitch=lock
#HandleLidSwitchDocked=ignore
#PowerKeyIgnoreInhibited=no
#SuspendKeyIgnoreInhibited=no
#HibernateKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
#HoldoffTimeoutSec=30s
#IdleAction=ignore
#IdleActionSec=30min
#RuntimeDirectorySize=10%
#RemoveIPC=yes
#InhibitorsMax=8192
#SessionsMax=8192
#UserTasksMax=33%

## !!!! Recommend you to reboot then!!!
```

### [参考] 可以修一下Nvidia阉割版Ubuntu
> https://www.malachisoord.com/2017/02/18/ubuntu-fix-wifi-after-suspend/

**Comment by Durant35** [comment]
##  E470 无线网卡驱动异常，上不网
+ 靠谱的[开源驱动](https://github.com/tomaspinho/rtl8821ce)
```bash
.../rtl8821ce-master$ sudo apt-get install dkms
.../rtl8821ce-master$ sudo ./dkms-install.sh
# Then reboot
```

###  VPN installed first, then faster `apt-get update`
+ 大概率会遇到以下问题：
 ```bash
.../rtl8821ce-master$ sudo apt-get install dkms 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dkms : Depends: dpkg-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

# 需要按照以下方式解决
$ sudo apt-get remove libdpkg-perl
# Recommend to install following one
$ sudo apt-get install build-essential
```

**Comment by Durant35** [comment]
## Build Wine-3.0.2 from [soure](https://dl.winehq.org/wine/source/3.0/wine-3.0.2.tar.xz)
> https://blog.csdn.net/qq_26056015/article/details/83061737

```bash
$ sudo apt install flex bison libx11-dev
$ ./configure
$ make
```

**Comment by Durant35** [comment]
## Video Player
+ Videos, also known as **Totem**, is the official movie player of the GNOME desktop environment. It features a searchable list of local videos, and DVDs, as well as local network video shares (using UPnP/DLNA) and video highlights from a number of web sites.

**Comment by Durant35** [comment]
## XXX-X AAC decoder, H.264 (Main Profile) decoder are required to play the file, but are not installed.
![image](https://user-images.githubusercontent.com/6770853/125544259-b0d400a5-6342-4c8f-b3b6-9369c280fe4d.png)

> https://blog.csdn.net/gisbbs/article/details/104474449

```bash
sudo apt install ubuntu-restricted-extras
```

**Comment by Durant35** [comment]
## Gnome Workspace多窗口

+ 安装 tweak-tool 等基础环境
    ```bash
    $ sudo apt-get install gnome-tweak-tool
    $ sudo apt install gnome-shell-extension-top-icons-plus
    ```

+ 下载 https://extensions.gnome.org/extension-data/workspace-grid%40mathematical.coffee.gmail.com.v29.shell-extension.zip （或者 https://github.com/zakkak/workspace-grid/releases/download/workspace-grid-for-3.30-b46/workspace-grid.mathematical.coffee.gmail.com.zip ）
    ```bash
    mkdir -p ~/.local/share/gnome-shell/extensions
    cd ~/.local/share/gnome-shell/extensions
    插件解压后mv进去即可
    ```
    ![image](https://github.com/user-attachments/assets/9bec3606-752f-447d-8a60-9bb5bddcb3bb)

+ 如找不到插件，一般需要重启电脑
    ![image](https://github.com/user-attachments/assets/3836916f-ad6b-44d6-9e5b-eee20247c3de)

**Comment by Durant35** [comment]
## 搜狗输入法
> https://shurufa.sogou.com/linux/guide

### 如遇到安装语言报错，建议重新安装dbus修复
```bash
sudo apt-get install --reinstall dbus
```

### [Ubuntu搜狗输入法安装指南和无法输入中文问题解决方案](https://blog.csdn.net/Bonaventure/article/details/136907414)
```bash
sudo apt install libgsettings-qt1
```

**Comment by Durant35** [comment]
## Terminal instead of Terminator
sudo update-alternatives --config x-terminal-emulator
